export default {
  id: "openai-compatible-chat-codecraft",
  priority: 25,
  alias: "codecraft",
  aliases: ["cc"],
  uiAlias: "CodeCraft",
  display: {
    name: "CodeCraft API",
    icon: "sparkles",
    color: "#D97757",
    website: "https://codecraftapi.com",
  },
  category: "apikey",
  transport: {
    baseUrl: "https://codecraftapi.com/v1/chat/completions",
    validateUrl: "https://codecraftapi.com/v1/models",
  },
  models: [
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna" },
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol" },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra" },
    { id: "gpt-5.5", name: "GPT-5.5" },
    { id: "gpt-5.5-pro", name: "GPT-5.5 Pro" },
    { id: "claude-fable-5", name: "Claude Fable 5" },
    { id: "claude-opus-5", name: "Claude Opus 5" },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5" },
    { id: "claude-mythos-preview", name: "Claude Mythos Preview" },
    { id: "claude-opus-4.8", name: "Claude Opus 4.8" },
    { id: "claude-opus-4.7", name: "Claude Opus 4.7" },
    { id: "claude-opus-4.6", name: "Claude Opus 4.6" },
    { id: "deepseek-v4-pro-max", name: "DeepSeek V4 Pro Max" },
    { id: "deepseek-v4-pro-0813", name: "DeepSeek V4 Pro" },
    { id: "deepseek-v4-flash-0731", name: "DeepSeek V4 Flash" },
    { id: "qwen3.8-max", name: "Qwen3.8 Max" },
    { id: "qwen3.8-27b", name: "Qwen3.8 27B" },
    { id: "qwen3.7-max", name: "Qwen3.7 Max" },
    { id: "gemini-3.7-flash", name: "Gemini 3.7 Flash" },
    { id: "gemini-3.6-flash", name: "Gemini 3.6 Flash" },
    { id: "gemini-3.1-pro", name: "Gemini 3.1 Pro" },
    { id: "glm-5.3", name: "GLM-5.3" },
    { id: "glm-5.2", name: "GLM-5.2" },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "grok-4.6", name: "Grok 4.6" },
    { id: "grok-4.5", name: "Grok 4.5" },
    { id: "seed-2.1-pro", name: "Seed 2.1 Pro" },
    { id: "seed-2.1-turbo", name: "Seed 2.1 Turbo" },
    { id: "muse-spark-1.1", name: "Muse Spark 1.1" },
    { id: "gemma-2-2b", name: "Gemma 2 2B" },
  ],
};
